# .github/ci.yaml
name: Basic CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: nightmare14226/ai-autofill-job-applying-chrome-extension@v1.0
      
      - name: Show basic info
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Event: ${{ github.event_name }}"
          echo "Repository: ${{ github.action_repository }}"
      - name: log
        run: ls -la